"""
Shared data loading utilities for the chemogenetic pipeline.
Handles CSV, PDB, and CIF file loading.
"""

import os
import pandas as pd

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def load_actuator_properties(path=None):
    """Load the actuator properties CSV generated by Module 2."""
    if path is None:
        path = os.path.join(PROJECT_ROOT, "data", "results", "actuator_properties.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Actuator properties not found at {path}. Run Module 2 first.")
    return pd.read_csv(path)


def load_compounds_csv(path=None):
    """Load the compounds definition CSV."""
    if path is None:
        path = os.path.join(PROJECT_ROOT, "data", "compounds", "compounds.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Compounds CSV not found at {path}.")
    return pd.read_csv(path)


def load_rmsd_results(path=None):
    """Load RMSD results CSV generated by Module 1."""
    if path is None:
        path = os.path.join(PROJECT_ROOT, "data", "results", "rmsd_results.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"RMSD results not found at {path}. Run Module 1 first.")
    return pd.read_csv(path)
